import 'package:flutter/material.dart';

/// 分类图标 key → IconData 映射（图标 key 存库，避免版本间图标名变化影响数据）。
const Map<String, IconData> _iconMap = {
  'help': Icons.help_outline,
  'capacitor': Icons.battery_charging_full,
  'resistor': Icons.tune,
  'inductor': Icons.waves,
  'diode': Icons.change_history,
  'transistor': Icons.control_camera,
  'mcu': Icons.memory,
  'logic': Icons.account_tree,
  'amplifier': Icons.graphic_eq,
  'power': Icons.bolt,
  'interface': Icons.settings_input_component,
  'storage': Icons.sd_storage,
  'converter': Icons.swap_horiz,
  'wireless': Icons.wifi,
  'clock': Icons.schedule,
  'sensor': Icons.sensors,
  'led': Icons.lightbulb,
  'connector': Icons.cable,
  'switch': Icons.toggle_on,
  'protect': Icons.security,
  'relay': Icons.settings_input_antenna,
  'module': Icons.developer_board,
  'battery': Icons.battery_full,
  'tool': Icons.handyman,
  'box': Icons.inventory_2_outlined,
  'folder': Icons.folder_outlined,
  'star': Icons.star_outline,
  'chip': Icons.developer_board,
};

/// 可选图标列表（新建/编辑分类时选择）。
const List<String> kSelectableIcons = [
  'capacitor',
  'resistor',
  'inductor',
  'diode',
  'transistor',
  'mcu',
  'logic',
  'amplifier',
  'power',
  'interface',
  'storage',
  'converter',
  'wireless',
  'clock',
  'sensor',
  'led',
  'connector',
  'switch',
  'protect',
  'relay',
  'module',
  'battery',
  'tool',
  'box',
  'folder',
  'star',
  'chip',
  'help',
];

IconData iconForKey(String? key) => _iconMap[key] ?? Icons.widgets_outlined;
